[Desktop Entry]
Name=System Profiler and Benchmark
Name[de]=System Profiler und Benchmark
Name[es]=Informacion y Rendimiento del Sistema
Name[fr]=Informations et Benchmarks du Système
Name[pt_BR]=Informações e Testes do Sistema
Name[ru]=Информация о системе и тестирование
Name[tr]=Sistem Bilgisi ve Karşılaştırma
Name[zh_CN]=系统信息
Comment=Displays system information
Comment[de]=Anzeigen von Systeminformationen
Comment[ru]=Показывает информацию о системе
Comment[zh_CN]=查看系统信息并运行基准测试
Exec=@CMAKE_INSTALL_FULL_BINDIR@/hardinfo
Icon=hardinfo
Terminal=false
Type=Application
StartupNotify=true
Categories=System;X-XFCE-SettingsDialog;X-XFCE-SystemSettings;
Keywords=linux;kernel;system;hardware;cpu;processor;capabilities;frequency;memory;ram;board;resources;sensors;devices;usb;pci;display;network;benchmark;test;
